Repository rancher/observability-e2e, pull requests merged in 2024-12, with the labels that each got.

#30 Fix project creation
  go.mod
  tests/e2e/installations_test.go
  tests/e2e/suite_test.go
Labels: bug, enhancement

#32 fix installation failure & session hang issue
  tests/e2e/installations_test.go
  tests/helper/charts/charts.go
Labels: Fix

#33 Added P0 tests for rancher alerts along with creation of alert manager config.
  tests/e2e/rancher_alerts_e2e_test.go
  tests/helper/utils/utils.go
  tests/helper/yamls/alertManagerConfig.yaml
Labels: alerting

#37 adding rancher logging P0 test along with minor cosmetic fixes
  tests/e2e/rancher_alerts_e2e_test.go
  tests/e2e/rancher_logging_e2e_test.go
Labels: logging
